version: "3.9"
services:
  csvserver:
    image: "infracloudio/csvserver:latest"
    volumes:
      - ./inputFile:/csvserver/inputdata
    ports:
      - "9393:9300"
    environment:
      CSVSERVER_BORDER: Orange
    container_name: csvserver

  prometheus:
    image: "prom/prometheus:v2.22.0"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    container_name: prometheus
