version: "3.9"
services:
  csvserver:
    image: "infracloudio/csvserver:latest"
    volumes:
      - ./inputFile:/csvserver/inputdata
    ports:
      - "9393:9300"
    environment:
      CSVSERVER_BORDER: Orange
    container_name: csvserver
